### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by schell** [noteed/language-glsl#14]
What's the status of this project? Is it/will it continue to be maintained?

**Comment by noteed** [comment]
Hi, I don't work on it but have accepted a PR or two in the past. I think the Elm project used it. Maybe they have forked it or have something else to replace it. Maybe you could ask them and report here ?

**Comment by schell** [comment]
Thank you, will do.

**Comment by schell** [comment]
It looks like `elm-compiler` is still using version 0.2 :)

**Comment by noteed** [comment]
Thanks for the heads up.

**Comment by David-Klemenc** [comment]
Elm now was updated to `language-glsl >= 0.3` in on Nov 16, 2018 [this commit](https://github.com/elm/compiler/commit/545e14d91a326c22b03594340694b21a5f7e1c74) 😄

**Comment by noteed** [comment]
Ah, thanks. And it seems the constraints were dropped here https://github.com/elm/compiler/commit/0421dfbe48e53d880a401e201890eac0b3de5f06.
