### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by MartinSStewart** [noteed/language-glsl#20]
Hello, I would like to try resolving this issue https://github.com/noteed/language-glsl/issues/4 (or at least enough to support `#extension`).

I'm stuck trying to build and run the tests for this repo though. When I run `cabal test` I get this error
```
PS C:\Users\Martin\Desktop\language-glsl> cabal test
Resolving dependencies...
Warning: solver failed to find a solution:
[__0] trying: language-glsl-0.3.0 (user goal)
line flag, or user target requires opposite flag selection)
[__1] trying: language-glsl:*test
[__2] unknown package: test-framework-hunit (dependency of language-glsl
*test)
[__1] fail (backjumping, conflict set: language-glsl, test-framework-hunit,
language-glsl:test)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: language-glsl, language-glsl:test,
test-framework-hunit
Trying configure anyway.
Configuring language-glsl-0.3.0...
cabal.exe: Encountered missing dependencies:
HUnit -any,
test-framework -any,
test-framework-hunit -any
```
(I get the same error for `cabal configure` and `cabal build`)

I'm new to haskell so maybe I'm missing something obvious.

GHC version: 8.4.3
cabal-install version 2.2.0.0

**Comment by noteed** [comment]
Hi,

I have pushed a new branch, https://github.com/noteed/language-glsl/tree/nixify, where I do two things:

- Add a `shell.nix` file so I can get the development dependencies easily.
- Update the `.cabal` file, mostly to match more recent projects of mine (I don't know if this makes a big difference here or not).

Using `nix-shell` (which will use the `shell.nix` file automatically), I get:

```
$ nix-shell
...
$ cabal test
...
Running 1 test suites...
Test suite tests: RUNNING...
Test suite tests: PASS
Test suite logged to:
/home/thu/projects/language-glsl/dist-newstyle/build/x86_64-linux/ghc-9.0.2/language-glsl-0.4.0.0/t/tests/test/language-glsl-0.4.0.0-tests.log
1 of 1 test suites (1 of 1 test cases) passed.

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.0.2

$ cabal --version
cabal-install version 3.6.2.0
compiled using version 3.6.3.0 of the Cabal library
```

Maybe in your case (without Nix), the changes to the `.cabal` file would be enough. Does it help ?

**Comment by noteed** [comment]
I also notice in your comment that Cabal doesn't seem to find some dependencies, which is weird. Did you run `cabal update` first ? See e.g. https://www.haskell.org/cabal/#troubleshooting

**Comment by MartinSStewart** [comment]
Thanks, I'll try the shell.nix and rerunning cabal later today. 

I did run cabal update and it did install a bunch of packages but I encountered the same error message when running cabal build/configure/test afterwards.

**Comment by noteed** [comment]
Just some other random though: if you have a `dist-newstyle/` directory in the current directory, naybe try to delete it before building again the project with Cabal.

**Comment by MartinSStewart** [comment]
Attempting cabal again on your fork didn't work but I managed to get it running by adding stack. I'll just make a PR once it's ready with the changes to src and tests though and leave the project config unchanged.

**Comment by MartinSStewart** [comment]
Since I was able to run tests, I'm going to close this issue.
